config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :question_categories
  end
  get 'faq', to: 'faqs#index'
end

app/models/spree/question.rb
class Spree::Question < ActiveRecord::Base
  acts_as_list

  belongs_to :question_category, class_name: 'Spree::QuestionCategory'

  validates :question_category_id, :question, :answer, presence: true
end

app/models/spree/question_category.rb
class Spree::QuestionCategory < ActiveRecord::Base
  acts_as_list

  has_many :questions, class_name: 'Spree::Question'

  validates :name, presence: true, uniqueness: true

  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/controllers/spree/admin/question_categories_controller.rb
module Spree
  module Admin
    class QuestionCategoriesController < ResourceController
      before_filter :question_category, only: [:new, :edit]

      private

      def question_category
        @question_category ||= @object
      end

      def question_category_params
        params.require(:question_category).permit(:questions_attributes, :question, :answer,
                       question: [:question_category_id, :question, :answer])
      end
    end
  end
end

app/controllers/spree/faqs_controller.rb
module Spree
  class FaqsController < StoreController
    helper 'spree/products'

    def index
      @categories = QuestionCategory.includes(:questions).load
    end

    def default_title
      Spree.t(:frequently_asked_questions, scope: :spree_faq)
    end
  end
end

app/views/admin/question_categories/new.js.erb
$("#new_question_category").html('<%= escape_javascript(render :template => "admin/question_categories/new.html.erb") %>');
handle_date_picker_fields();
$("#admin_new_question_category").parent().hide();

app/views/spree/admin/question_categories/_question.html.erb
<div class="question" id="<%= dom_id f.object %>">
	<fieldset class="no-border-bottom">
	  <div class="field">
	    <%= f.label :question, Spree::Question.model_name.human(count: 1) %> <span class="required">*</span><br />
	    <%= f.text_field :question, class: 'fullwidth title' %>
	  </div>
	  <div class="field">
	    <%= f.label :answer, Spree.t(:answer, scope: :spree_faq) %> <span class="required">*</span><br />
	    <%= f.text_area :answer, rows: 2, class: 'fullwidth' %>
	  </div>
	  <%= f.hidden_field :_destroy %>
	  <%= link_to_with_icon 'icon-trash', 'remove', '#', class: 'remove' %>
  </fieldset>
</div>

app/views/spree/admin/question_categories/edit.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_category_questions, scope: :spree_faq) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:add_question, scope: :spree_faq), '#', icon: 'icon-plus', id: 'new_question_link' %>
    <%= button_link_to Spree.t(:back_to_categories, scope: :spree_faq), spree.admin_question_categories_path, icon: 'icon-arrow-left' %>
  </li>
<% end %>

<%= render 'spree/shared/error_messages', target: @question_category %>

<%= form_for [:admin, @question_category] do |f| %>
  <%= javascript_tag do %>
     var new_question_html = '<%= generate_template(f, :questions) %>';
  <% end %>
  <div class="field">
    <%= f.field_container :name do %>
      <%= f.label :name, Spree.t(:category_name, scope: :spree_faq) %> <span class="required">*</span><br />
      <%= f.text_field :name, class: 'fullwidth title' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
  <div id="questions" style="margin-bottom: 20px">
    <h3>Questions</h3>
      <%= f.fields_for :questions do |question_form| %>
        <%= render 'question', f: question_form %>
      <% end %>
  </div>
  <div class="form-buttons filter-actions actions" data-hook="buttons">
    <%= button Spree.t(:update), 'icon-refresh' %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= link_to_with_icon 'icon-remove', Spree.t(:cancel), admin_question_categories_url, class: 'button' %>
  </div>
<% end %>

app/views/spree/admin/question_categories/index.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:question_categories, scope: :spree_faq) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_question_category_link">
    <%= button_link_to Spree.t(:new_question_category, scope: :spree_faq), new_admin_question_category_url,
        { remote: true, icon: 'icon-plus', 'data-update' => 'new_question_category', id: 'new_question_category_link' } %>
  </li>
<% end %>

<div id="new_question_category"></div>

<% if @question_categories.any? %>
<table class="index" id="listing_faq">
  <colgroup>
    <col style="width: 40%">
    <col style="width: 40%">
    <col style="width: 20%">
  </colgroup>
  <thead>
    <tr data-hook="admin_faq_category_index_headers">
      <th><%= Spree::QuestionCategory.model_name.human(count: 2) %></td>
      <th><%= Spree::Question.model_name.human(count: 2) %></td>
      <th data-hook="admin_faq_category_index_header_actions" class="actions"></th>
    </tr>
  <thead>
  <tbody>
    <% @question_categories.each do |category| %>
      <tr id="<%= spree_dom_id category %>" data-hook="admin_faq_category_index_rows" class="<%= cycle('odd', 'even') %>">
        <td class="align-center"><%= h category.name %></td>
        <td class="align-center"><%= category.questions.count %></td>
        <td data-hook="admin_faq_category_index_row_actions" class="actions">
          <%= link_to_edit category, no_text: true %>
          <%= link_to_delete category, no_text: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree::QuestionCategory.model_name.human(count: 2)) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_question_category_path %>!
  </div>
<% end %>

app/views/spree/admin/question_categories/new.html.erb
<%= render 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_question_category, scope: :spree_faq) %>
<% end %>

<%= render 'spree/shared/error_messages', target: @question_category %>
<%= form_for [:admin, @question_category] do |f| %>
  <fieldset class="no-border-top">
      <%= f.field_container :name do %>
          <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
          <%= f.text_field :name, class: 'fullwidth title'  %>
          <%= f.error_message_on :name %>
      <% end %>
      <div data-hook="buttons" class="filter-actions actions">
      	<%= button Spree.t(:create), 'icon-ok' %>
    	</div>
  </fieldset>
<% end %>

app/views/spree/admin/question_categories/new.js.erb
$('#new_question_category').html('<%= escape_javascript(render template: "spree/admin/question_categories/new", formats: [:html], handlers: [:erb]) %>');
$('#new_question_category_link').parent().hide();

app/views/spree/faqs/index.html.erb
<h1><%= Spree.t(:frequently_asked_questions, scope: :spree_faq) %></h1>

<div id="faqs">
  <% @categories.each do |category| %>
    <div id="<%= dom_id category -%>" class="category">
      <h2><%= h category.name %></h2>
      <ul class="answers">
        <% category.questions.each do |question| %>
          <li>
            <a class="question" id="<%= dom_id question -%>" href="#<%= "answer_#{question.id}" %>">
              <%= raw(question.question) -%>
            </a>
            <div class="answer" id="<%= "answer_#{question.id}"-%>">
              <%= raw(question.answer) %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<% content_for :sidebar do %>
  <% if defined? @products && defined? @taxon %>
    <%= render 'spree/shared/filters' %>
  <% elsif defined? @taxonomies %>
    <%= render 'spree/shared/taxonomies' %>
  <% end %>
<% end %>